import { describe, test, expect } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";

describe("WASM AOT Generated Code", () => {
    test("load and execute test_add.wasm", async () => {
        const wasmPath = path.join(import.meta.dir, "../../artifacts/test_add.wasm");
        
        // Check if file exists (it should be generated by 'zig build test')
        if (!fs.existsSync(wasmPath)) {
            console.warn("Skipping WASM test: artifact not found. Run 'zig build test' first.");
            return;
        }
        
        const buffer = fs.readFileSync(wasmPath);
        const module = await WebAssembly.compile(buffer);
        const instance = await WebAssembly.instantiate(module);
        
        const add = instance.exports.add as (a: number, b: number) => number;
        expect(add).toBeDefined();
        expect(add(10, 20)).toBe(30);
        expect(add(1.5, 2.5)).toBe(4.0);
    });

    test("load and execute test_compile.wasm (a + b * 2.5)", async () => {
        const wasmPath = path.join(import.meta.dir, "../../artifacts/test_compile.wasm");
        
        if (!fs.existsSync(wasmPath)) {
            console.warn("Skipping WASM test: artifact not found.");
            return;
        }
        
        const buffer = fs.readFileSync(wasmPath);
        const module = await WebAssembly.compile(buffer);
        const instance = await WebAssembly.instantiate(module);
        
        // Export name is "calc" as specified in zig test
        const calc = instance.exports.calc as (a: number, b: number) => number;
        expect(calc).toBeDefined();
        
        const r1 = calc(10, 20);
        const r2 = calc(2, 4);
        expect(Number.isFinite(r1)).toBe(true);
        expect(Number.isFinite(r2)).toBe(true);
    });
});
