/**
 * Static data loaders for apps/progress/public/data/*.json
 * Generated by: bun run mz (or bun run --cwd apps/progress app-data)
 */

export type PackageStatus = "pass" | "fail" | "partial";
export type PackageKind = "dev" | "release" | "failed";
export type BenchMode = "zig" | "ts" | "all";
export type CorrectnessOverall = "pass" | "fail";
export type PerformanceStatus = "ok" | "skipped" | "error";
export type StepStatus = "pass" | "fail" | "skipped";

export type ProgressIndexEntry = {
  version_id: string;
  seq: number;
  sort_key: string;
  label: string;
  kind: PackageKind;
  status: PackageStatus;
  feature_id: string;
  git_sha: string;
  git_tag: string | null;
  recorded_at: string;
  machine_id: string;
  has_performance: boolean;
  tier: string;
  bench_mode: BenchMode;
  path: string;
  source: "local" | "release";
};

export type AppDataIndex = {
  schema_version: 1;
  generated_at: string;
  package_count: number;
  machine_ids: string[];
  mixed_machines: boolean;
  packages: ProgressIndexEntry[];
};

export type AppDataSeriesPoint = {
  seq: number;
  version_id: string;
  score: number;
  threads: number;
  unit: string;
  machine_id: string;
  recorded_at: string;
  feature_id: string;
};

export type AppDataSeries = {
  schema_version: 1;
  generated_at: string;
  series: Record<string, Record<string, AppDataSeriesPoint[]>>;
};

export type StatusHistogram = {
  done: number;
  partial: number;
  broken: number;
  skipped: number;
  missing: number;
  "n/a": number;
  unknown: number;
};

export type FeatureCellBackend = {
  status: string;
  pass?: number;
  fail?: number;
  skip?: number;
  evidence: string;
};

export type FeatureCell = {
  feature_id: string;
  category: string;
  label: string;
  related_bench_ids: string[];
  by_backend: Record<string, FeatureCellBackend>;
};

export type FeaturesDocument = {
  schema_version: 1;
  version_id: string;
  seq?: number;
  generated_at: string;
  catalog_hash: string;
  backends: string[];
  backends_executed: string[];
  cells: FeatureCell[];
  summary: Record<string, StatusHistogram>;
};

/** Slim meta as written by build_app_data (full MetaDocument). */
export type SlimMeta = {
  schema_version?: number;
  version_id: string;
  seq: number;
  sort_key?: string;
  label: string;
  kind: PackageKind;
  status: PackageStatus;
  feature_id: string;
  git_sha: string;
  git_sha_full?: string;
  git_tag: string | null;
  recorded_at: string;
  gate_started_at?: string;
  machine_id: string;
  cpu_model?: string;
  cpu_cores?: number;
  os?: string;
  zig_version?: string;
  bun_version?: string;
  mathzig_version?: string;
  baseline_feature_id?: string | null;
  baseline_version_id?: string | null;
  tier: string;
  bench_mode: BenchMode;
  has_performance: boolean;
  bench_snapshot_id?: string | null;
  gate_run_dir?: string;
  parity_backends_executed?: string[];
};

export type SlimCorrectnessStep = {
  id: string;
  status: StepStatus;
  duration_sec: number | null;
  reason: string | null;
};

export type SlimCorrectness = {
  overall: CorrectnessOverall;
  gate_started_at: string;
  steps: SlimCorrectnessStep[];
  parity?: {
    task_id: string;
    backends_executed: string[];
    backends: Record<
      string,
      {
        pass: number;
        fail: number;
        skip: number;
        total: number;
        missing?: boolean;
      }
    >;
    backends_not_executed: string[];
  };
};

export type SlimFeatures = {
  version_id: string;
  seq?: number;
  catalog_hash: string;
  backends: string[];
  backends_executed: string[];
  summary: Record<string, StatusHistogram>;
  cell_count: number;
};

export type SlimPerformanceResult = {
  bench_id: string;
  backend: string;
  threads: number;
  score: number;
  unit: string;
  ops_p50?: number;
  ops_p95?: number;
  sample_count?: number;
};

export type SlimPerformance = {
  status: PerformanceStatus;
  reason?: string;
  snapshot_id?: string | null;
  results: SlimPerformanceResult[];
};

export type SlimPackage = {
  meta: SlimMeta;
  correctness: SlimCorrectness;
  features: SlimFeatures | null;
  performance: SlimPerformance;
};

export type AppDataPackages = {
  schema_version: 1;
  generated_at: string;
  packages: Record<string, SlimPackage>;
};

const DATA_BASE = "/data";

export const NO_DATA_HINT = "no data — run bun run mz (or bun run --cwd apps/progress app-data)";

/** Display labels for perf backends (overview / version detail tables). */
export const PERF_BACKEND_LABELS: Record<string, string> = {
  mathzig_zig: "Zig VM (perf)",
  mathzig_ffi: "TS FFI (perf)",
  native_js: "Native JS",
  ref_zig: "Ref Zig",
  ref_c: "Ref C",
};

/** Display labels for parity / feature-matrix backends (§D.6). */
export const PARITY_BACKEND_LABELS: Record<string, string> = {
  zig_vm: "Zig VM",
  ts_ffi: "TS FFI",
  ts_wasm_vm: "TS WASM VM",
  wasm_aot: "WASM AOT",
};

/** Default matrix column order when document omits backends. */
export const DEFAULT_FEATURE_BACKENDS = [
  "zig_vm",
  "ts_ffi",
  "ts_wasm_vm",
  "wasm_aot",
] as const;

/** All feature cell statuses (legend order). */
export const FEATURE_STATUSES = [
  "done",
  "partial",
  "missing",
  "skipped",
  "broken",
  "n/a",
  "unknown",
] as const;

export type FeatureStatusName = (typeof FEATURE_STATUSES)[number];

export type FeaturesLoadResult =
  | { ok: true; data: FeaturesDocument }
  | { ok: false; message: string };

/** % unknown split by whether the backend was executed this version. */
export type UnknownBadge = {
  executed_total: number;
  executed_unknown: number;
  executed_pct: number | null;
  not_executed_total: number;
  not_executed_unknown: number;
  not_executed_pct: number | null;
  overall_total: number;
  overall_unknown: number;
  overall_pct: number | null;
};

/** Ratio denominators: show column only when baseline exists for bench+threads. */
export const RATIO_BASELINES = [
  { backend: "mathzig_zig", column: "vs zig" },
  { backend: "native_js", column: "vs js" },
  { backend: "ref_zig", column: "vs ref_zig" },
  { backend: "ref_c", column: "vs ref_c" },
] as const;

export class DataLoadError extends Error {
  status?: number;
  path?: string;

  constructor(message: string, status?: number, path?: string) {
    super(message);
    this.name = "DataLoadError";
    this.status = status;
    this.path = path;
  }
}

export type IndexLoadResult =
  | { ok: true; data: AppDataIndex }
  | { ok: false; message: string };

export type PackagesLoadResult =
  | { ok: true; data: AppDataPackages }
  | { ok: false; message: string };

export type SeriesLoadResult =
  | { ok: true; data: AppDataSeries }
  | { ok: false; message: string };

/** Client-side pairwise row (pct delta from package scores; not full SoT compare). */
export type ClientCompareStatus =
  | "OK"
  | "REGRESSION"
  | "IMPROVEMENT"
  | "MISSING_BASELINE"
  | "MISSING_AFTER"
  | "NEW";

export type ClientCompareRow = {
  bench_id: string;
  backend: string;
  threads: number;
  unit: string;
  baseline_score: number | null;
  after_score: number | null;
  pct_delta: number | null;
  threshold_pct: number;
  status: ClientCompareStatus;
};

/** One line on a trend chart: backend@threads over package seq. */
export type TrendLine = {
  key: string;
  backend: string;
  threads: number;
  unit: string;
  points: Array<{
    seq: number;
    version_id: string;
    score: number;
    recorded_at: string;
    feature_id: string;
  }>;
};

/** Default relative regression threshold (%) — higher score is better (ops/s). */
export const DEFAULT_REGRESSION_THRESHOLD_PCT = 5;

async function fetchJson<T>(path: string): Promise<T> {
  const url = path.startsWith("/") ? path : `${DATA_BASE}/${path}`;
  let res: Response;
  try {
    res = await fetch(url);
  } catch (err) {
    throw new DataLoadError(
      `Failed to fetch ${url}: ${err instanceof Error ? err.message : String(err)}`,
      undefined,
      url
    );
  }
  if (!res.ok) {
    throw new DataLoadError(
      res.status === 404
        ? `Missing ${url} (${NO_DATA_HINT})`
        : `HTTP ${res.status} loading ${url}`,
      res.status,
      url
    );
  }
  return (await res.json()) as T;
}

/** Load package index (primary entry for all pages). */
export function loadIndex(): Promise<AppDataIndex> {
  return fetchJson<AppDataIndex>(`${DATA_BASE}/index.json`);
}

/** Load precomputed perf trend series. */
export function loadSeries(): Promise<AppDataSeries> {
  return fetchJson<AppDataSeries>(`${DATA_BASE}/series.json`);
}

/** Load slim package map (version_id → package). */
export function loadPackages(): Promise<AppDataPackages> {
  return fetchJson<AppDataPackages>(`${DATA_BASE}/packages.json`);
}

/** Load full feature matrix for the latest package. */
export function loadFeaturesLatest(): Promise<FeaturesDocument> {
  return fetchJson<FeaturesDocument>(`${DATA_BASE}/features_latest.json`);
}

/** Auto compare: latest package vs previous (written by `bun run mz` / build_app_data). */
export type LatestCompareDocument = {
  schema_version: 1;
  generated_at: string;
  status: "ok" | "insufficient" | "error";
  reason?: string;
  after_version_id: string | null;
  baseline_version_id: string | null;
  after_automatic_tag: string | null;
  baseline_automatic_tag: string | null;
  machine_id: string | null;
  failure_count: number;
  compare: {
    rows: Array<{
      test_name: string;
      bench_id: string;
      backend: string;
      threads: number;
      baseline_score: number | null;
      after_score: number | null;
      pct_delta: number | null;
      threshold_pct: number;
      status: string;
    }>;
    failure_count: number;
    max_regression_pct: number;
  } | null;
};

export function loadLatestCompare(): Promise<LatestCompareDocument> {
  return fetchJson<LatestCompareDocument>(`${DATA_BASE}/latest_compare.json`);
}

export type LatestCompareLoadResult =
  | { ok: true; data: LatestCompareDocument }
  | { ok: false; message: string };

export async function tryLoadLatestCompare(): Promise<LatestCompareLoadResult> {
  try {
    const data = await loadLatestCompare();
    return { ok: true, data };
  } catch (err) {
    if (err instanceof DataLoadError && err.status === 404) {
      return { ok: false, message: NO_DATA_HINT };
    }
    return {
      ok: false,
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

/** Map server SoT compare rows → client table rows. */
export function latestCompareToClientRows(
  doc: LatestCompareDocument
): ClientCompareRow[] {
  if (doc.status !== "ok" || !doc.compare?.rows) return [];
  return doc.compare.rows.map((r) => {
    const pct = r.pct_delta;
    let status: ClientCompareStatus = "OK";
    if (r.status.includes("REGRESSION")) status = "REGRESSION";
    else if (r.status === "MISSING_AFTER") status = "MISSING_AFTER";
    else if (r.status === "NEW_IN_AFTER") status = "NEW";
    else if (r.baseline_score == null) status = "MISSING_BASELINE";
    else if (pct != null && Number.isFinite(pct) && pct > (r.threshold_pct ?? 5)) {
      status = "IMPROVEMENT";
    } else if (r.status === "OK" || r.status === "UNSTABLE") {
      status = "OK";
    }
    return {
      bench_id: r.bench_id || r.test_name,
      backend: r.backend || "?",
      threads: r.threads ?? 0,
      unit: "ops/s",
      baseline_score: r.baseline_score,
      after_score: r.after_score,
      pct_delta: pct,
      threshold_pct: r.threshold_pct ?? DEFAULT_REGRESSION_THRESHOLD_PCT,
      status,
    };
  });
}

export async function tryLoadFeaturesLatest(): Promise<FeaturesLoadResult> {
  try {
    const data = await loadFeaturesLatest();
    return { ok: true, data };
  } catch (err) {
    if (err instanceof DataLoadError && err.status === 404) {
      return { ok: false, message: NO_DATA_HINT };
    }
    return {
      ok: false,
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

export function featuresData(result: FeaturesLoadResult): FeaturesDocument | null {
  return result.ok ? result.data : null;
}

export function parityBackendLabel(backend: string): string {
  return PARITY_BACKEND_LABELS[backend] ?? backend;
}

/** Matrix column ids from document (fallback default parity set). */
export function featureBackends(doc: FeaturesDocument): string[] {
  if (doc.backends?.length) return [...doc.backends];
  return [...DEFAULT_FEATURE_BACKENDS];
}

function pct(part: number, total: number): number | null {
  if (total <= 0) return null;
  return (part / total) * 100;
}

/**
 * Count unknown cells among executed backends vs not-executed backends.
 * Empty matrix → zeros with null percentages.
 */
export function unknownStatusBadge(doc: FeaturesDocument): UnknownBadge {
  const executed = new Set(doc.backends_executed ?? []);
  const backends = featureBackends(doc);
  let executed_total = 0;
  let executed_unknown = 0;
  let not_executed_total = 0;
  let not_executed_unknown = 0;

  for (const cell of doc.cells ?? []) {
    for (const backend of backends) {
      const status = cell.by_backend?.[backend]?.status ?? "unknown";
      if (executed.has(backend)) {
        executed_total++;
        if (status === "unknown") executed_unknown++;
      } else {
        not_executed_total++;
        if (status === "unknown") not_executed_unknown++;
      }
    }
  }

  const overall_total = executed_total + not_executed_total;
  const overall_unknown = executed_unknown + not_executed_unknown;

  return {
    executed_total,
    executed_unknown,
    executed_pct: pct(executed_unknown, executed_total),
    not_executed_total,
    not_executed_unknown,
    not_executed_pct: pct(not_executed_unknown, not_executed_total),
    overall_total,
    overall_unknown,
    overall_pct: pct(overall_unknown, overall_total),
  };
}

/** Unique categories from matrix cells, sorted. */
export function featureCategories(cells: FeatureCell[]): string[] {
  const set = new Set<string>();
  for (const c of cells) {
    if (c.category) set.add(c.category);
  }
  return [...set].sort((a, b) => a.localeCompare(b));
}

export function formatPct(value: number | null | undefined, digits = 0): string {
  if (value === null || value === undefined || !Number.isFinite(value)) return "—";
  return `${value.toFixed(digits)}%`;
}

/**
 * Convenience: try loadIndex, return null-style result on missing/error.
 * Pages use this for stub "no data" messaging.
 */
export async function tryLoadIndex(): Promise<IndexLoadResult> {
  try {
    const data = await loadIndex();
    return { ok: true, data };
  } catch (err) {
    if (err instanceof DataLoadError && err.status === 404) {
      return { ok: false, message: NO_DATA_HINT };
    }
    return {
      ok: false,
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

export async function tryLoadPackages(): Promise<PackagesLoadResult> {
  try {
    const data = await loadPackages();
    return { ok: true, data };
  } catch (err) {
    if (err instanceof DataLoadError && err.status === 404) {
      return { ok: false, message: NO_DATA_HINT };
    }
    return {
      ok: false,
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

export async function tryLoadSeries(): Promise<SeriesLoadResult> {
  try {
    const data = await loadSeries();
    return { ok: true, data };
  } catch (err) {
    if (err instanceof DataLoadError && err.status === 404) {
      return { ok: false, message: NO_DATA_HINT };
    }
    return {
      ok: false,
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

export function seriesData(result: SeriesLoadResult): AppDataSeries | null {
  return result.ok ? result.data : null;
}

export function indexMessage(result: IndexLoadResult): string {
  return result.ok ? "" : result.message;
}

export function indexData(result: IndexLoadResult): AppDataIndex | null {
  return result.ok ? result.data : null;
}

export function packagesData(result: PackagesLoadResult): AppDataPackages | null {
  return result.ok ? result.data : null;
}

/** Index entry with maximum seq (latest package). */
export function latestIndexEntry(
  index: AppDataIndex
): ProgressIndexEntry | null {
  if (!index.packages.length) return null;
  let best = index.packages[0]!;
  for (const p of index.packages) {
    if (p.seq > best.seq) best = p;
  }
  return best;
}

/** Unique thread counts from performance results, sorted ascending. */
export function uniqueThreads(results: SlimPerformanceResult[]): number[] {
  const set = new Set<number>();
  for (const r of results) set.add(r.threads);
  return [...set].sort((a, b) => a - b);
}

/**
 * Default thread filter: prefer 1 when multiple thread values exist;
 * otherwise the sole value (or 1 if empty).
 */
export function defaultThreadFilter(threads: number[]): number {
  if (threads.length === 0) return 1;
  if (threads.length === 1) return threads[0]!;
  if (threads.includes(1)) return 1;
  return threads[0]!;
}

/** Map (bench_id, threads, backend) → score for ratio lookups. */
export function scoreLookup(
  results: SlimPerformanceResult[]
): Map<string, number> {
  const map = new Map<string, number>();
  for (const r of results) {
    map.set(`${r.bench_id}\0${r.threads}\0${r.backend}`, r.score);
  }
  return map;
}

export function ratioKey(
  benchId: string,
  threads: number,
  backend: string
): string {
  return `${benchId}\0${threads}\0${backend}`;
}

/** Format ops/s-style scores compactly. */
export function formatScore(score: number): string {
  if (!Number.isFinite(score)) return "—";
  if (Math.abs(score) >= 1e9) return `${(score / 1e9).toFixed(2)}e9`;
  if (Math.abs(score) >= 1e6) return `${(score / 1e6).toFixed(2)}e6`;
  if (Math.abs(score) >= 1e3) return `${(score / 1e3).toFixed(2)}e3`;
  if (Math.abs(score) >= 100) return score.toFixed(1);
  if (Math.abs(score) >= 1) return score.toFixed(2);
  return score.toPrecision(3);
}

/** Format score/baseline ratio (higher is better for ops/s). */
export function formatRatio(score: number, baseline: number): string {
  if (!Number.isFinite(score) || !Number.isFinite(baseline) || baseline === 0) {
    return "—";
  }
  const r = score / baseline;
  if (r >= 100) return r.toFixed(0) + "×";
  if (r >= 10) return r.toFixed(1) + "×";
  return r.toFixed(2) + "×";
}

export function backendLabel(backend: string): string {
  return PERF_BACKEND_LABELS[backend] ?? backend;
}

export function packagesSortedBySeqDesc(
  packages: ProgressIndexEntry[]
): ProgressIndexEntry[] {
  return [...packages].sort((a, b) => {
    if (b.seq !== a.seq) return b.seq - a.seq;
    return b.version_id.localeCompare(a.version_id);
  });
}

export function packagesSortedBySeqAsc(
  packages: ProgressIndexEntry[]
): ProgressIndexEntry[] {
  return [...packages].sort((a, b) => {
    if (a.seq !== b.seq) return a.seq - b.seq;
    return a.version_id.localeCompare(b.version_id);
  });
}

/** Sorted bench_id keys from series.json. */
export function seriesBenchIds(series: AppDataSeries): string[] {
  return Object.keys(series.series).sort((a, b) => a.localeCompare(b));
}

/** Machine ids appearing in series points for a given bench (or all benches). */
export function seriesMachineIds(
  series: AppDataSeries,
  benchId?: string
): string[] {
  const set = new Set<string>();
  const benches =
    benchId && series.series[benchId]
      ? { [benchId]: series.series[benchId]! }
      : series.series;
  for (const byBackend of Object.values(benches)) {
    for (const points of Object.values(byBackend)) {
      for (const p of points) {
        if (p.machine_id) set.add(p.machine_id);
      }
    }
  }
  return [...set].sort((a, b) => a.localeCompare(b));
}

/**
 * Hard-default machine for filtering: first index.machine_ids entry,
 * else first machine seen in packages/series.
 */
export function defaultMachineId(
  index: AppDataIndex,
  fallbackIds: string[] = []
): string | null {
  if (index.machine_ids.length > 0) return index.machine_ids[0]!;
  if (fallbackIds.length > 0) return fallbackIds[0]!;
  return null;
}

export function trendLineKey(backend: string, threads: number): string {
  return `${backend}@t${threads}`;
}

/**
 * Build trend lines for one bench_id: one series per backend@threads.
 * Points ordered by seq ascending. Optional machine filter.
 */
export function buildTrendLines(
  series: AppDataSeries,
  benchId: string,
  machineId: string | null
): TrendLine[] {
  const byBackend = series.series[benchId];
  if (!byBackend) return [];

  const lines = new Map<string, TrendLine>();

  for (const [backend, points] of Object.entries(byBackend)) {
    for (const p of points) {
      if (machineId && p.machine_id !== machineId) continue;
      const key = trendLineKey(backend, p.threads);
      let line = lines.get(key);
      if (!line) {
        line = {
          key,
          backend,
          threads: p.threads,
          unit: p.unit,
          points: [],
        };
        lines.set(key, line);
      }
      line.points.push({
        seq: p.seq,
        version_id: p.version_id,
        score: p.score,
        recorded_at: p.recorded_at,
        feature_id: p.feature_id,
      });
    }
  }

  const out = [...lines.values()];
  for (const line of out) {
    line.points.sort((a, b) => {
      if (a.seq !== b.seq) return a.seq - b.seq;
      return a.version_id.localeCompare(b.version_id);
    });
  }
  out.sort((a, b) => {
    const bc = a.backend.localeCompare(b.backend);
    if (bc !== 0) return bc;
    return a.threads - b.threads;
  });
  return out;
}

/** Stable color for a trend line key (backend@threads). */
export const TREND_COLORS = [
  "#5eb8e8", // keyword-ish
  "#6dd4a0", // ok/number
  "#e0b050", // warn
  "#c79bff", // variable
  "#e88870", // err-ish
  "#7ec8c8", // type
  "#e0c870", // function
  "#9aa8c0", // muted
] as const;

export function trendColor(index: number): string {
  return TREND_COLORS[index % TREND_COLORS.length]!;
}

/**
 * Packages with has_performance on a machine, newest first (seq desc).
 * If machineId is null, include all machines.
 */
export function packagesWithPerformance(
  index: AppDataIndex,
  machineId: string | null
): ProgressIndexEntry[] {
  return packagesSortedBySeqDesc(
    index.packages.filter((p) => {
      if (!p.has_performance) return false;
      if (machineId && p.machine_id !== machineId) return false;
      return true;
    })
  );
}

/**
 * Pick latest + previous package for regression board on the same machine.
 * Returns null pair members when fewer than needed packages exist.
 */
export function regressionPair(
  index: AppDataIndex,
  machineId: string | null
): { after: ProgressIndexEntry | null; baseline: ProgressIndexEntry | null } {
  const list = packagesWithPerformance(index, machineId);
  return {
    after: list[0] ?? null,
    baseline: list[1] ?? null,
  };
}

function resultKey(benchId: string, backend: string, threads: number): string {
  return `${benchId}\0${backend}\0${threads}`;
}

/**
 * Client-side pct deltas between two package performance payloads.
 * Higher score is better (ops/s). REGRESSION when pct_delta < -threshold.
 * Prefer this when performance_compare is not embedded in app data.
 */
export function comparePerformanceClient(
  baselineResults: SlimPerformanceResult[],
  afterResults: SlimPerformanceResult[],
  thresholdPct: number = DEFAULT_REGRESSION_THRESHOLD_PCT
): ClientCompareRow[] {
  const base = new Map<string, SlimPerformanceResult>();
  for (const r of baselineResults) {
    base.set(resultKey(r.bench_id, r.backend, r.threads), r);
  }
  const after = new Map<string, SlimPerformanceResult>();
  for (const r of afterResults) {
    after.set(resultKey(r.bench_id, r.backend, r.threads), r);
  }

  const keys = [...new Set([...base.keys(), ...after.keys()])].sort((a, b) =>
    a.localeCompare(b)
  );

  const rows: ClientCompareRow[] = [];
  for (const key of keys) {
    const b = base.get(key);
    const a = after.get(key);
    const bench_id = a?.bench_id ?? b!.bench_id;
    const backend = a?.backend ?? b!.backend;
    const threads = a?.threads ?? b!.threads;
    const unit = a?.unit ?? b?.unit ?? "ops/s";

    if (b && !a) {
      rows.push({
        bench_id,
        backend,
        threads,
        unit,
        baseline_score: b.score,
        after_score: null,
        pct_delta: null,
        threshold_pct: thresholdPct,
        status: "MISSING_AFTER",
      });
      continue;
    }
    if (!b && a) {
      rows.push({
        bench_id,
        backend,
        threads,
        unit,
        baseline_score: null,
        after_score: a.score,
        pct_delta: null,
        threshold_pct: thresholdPct,
        status: "NEW",
      });
      continue;
    }
    if (!b || !a) continue;

    const pct =
      b.score === 0 ? 0 : ((a.score - b.score) / b.score) * 100;
    let status: ClientCompareStatus = "OK";
    if (pct < -thresholdPct) status = "REGRESSION";
    else if (pct > thresholdPct) status = "IMPROVEMENT";

    rows.push({
      bench_id,
      backend,
      threads,
      unit,
      baseline_score: b.score,
      after_score: a.score,
      pct_delta: pct,
      threshold_pct: thresholdPct,
      status,
    });
  }

  rows.sort((x, y) => {
    const bc = x.bench_id.localeCompare(y.bench_id);
    if (bc !== 0) return bc;
    const be = x.backend.localeCompare(y.backend);
    if (be !== 0) return be;
    return x.threads - y.threads;
  });
  return rows;
}

/** Format signed percentage delta for tables. */
export function formatPctDelta(pct: number | null | undefined): string {
  if (pct === null || pct === undefined || !Number.isFinite(pct)) return "—";
  const sign = pct > 0 ? "+" : "";
  if (Math.abs(pct) >= 100) return `${sign}${pct.toFixed(0)}%`;
  if (Math.abs(pct) >= 10) return `${sign}${pct.toFixed(1)}%`;
  return `${sign}${pct.toFixed(2)}%`;
}

/** Aggregate feature status histogram across backends. */
export function aggregateStatusHistogram(
  summary: Record<string, StatusHistogram> | undefined
): StatusHistogram {
  const totals: StatusHistogram = {
    done: 0,
    partial: 0,
    broken: 0,
    skipped: 0,
    missing: 0,
    "n/a": 0,
    unknown: 0,
  };
  if (!summary) return totals;
  for (const hist of Object.values(summary)) {
    for (const key of Object.keys(totals) as Array<keyof StatusHistogram>) {
      totals[key] += hist[key] ?? 0;
    }
  }
  return totals;
}

export const HISTOGRAM_KEYS: Array<keyof StatusHistogram> = [
  "done",
  "partial",
  "broken",
  "skipped",
  "missing",
  "n/a",
  "unknown",
];
